# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class AllowHemsRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, device_ssa=None, serial_number=None, allow_hems=None):  # noqa: E501
        """AllowHemsRequestBody - a model defined in OpenAPI

        :param device_ssa: The device_ssa of this AllowHemsRequestBody.  # noqa: E501
        :type device_ssa: str
        :param serial_number: The serial_number of this AllowHemsRequestBody.  # noqa: E501
        :type serial_number: str
        :param allow_hems: The allow_hems of this AllowHemsRequestBody.  # noqa: E501
        :type allow_hems: bool
        """
        self.openapi_types = {
            'device_ssa': str,
            'serial_number': str,
            'allow_hems': bool
        }

        self.attribute_map = {
            'device_ssa': 'device_ssa',
            'serial_number': 'serial_number',
            'allow_hems': 'allow_hems'
        }

        self._device_ssa = device_ssa
        self._serial_number = serial_number
        self._allow_hems = allow_hems

    @classmethod
    def from_dict(cls, dikt) -> 'AllowHemsRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllowHemsRequestBody of this AllowHemsRequestBody.  # noqa: E501
        :rtype: AllowHemsRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device_ssa(self):
        """Gets the device_ssa of this AllowHemsRequestBody.


        :return: The device_ssa of this AllowHemsRequestBody.
        :rtype: str
        """
        return self._device_ssa

    @device_ssa.setter
    def device_ssa(self, device_ssa):
        """Sets the device_ssa of this AllowHemsRequestBody.


        :param device_ssa: The device_ssa of this AllowHemsRequestBody.
        :type device_ssa: str
        """
        if device_ssa is None:
            raise ValueError("Invalid value for `device_ssa`, must not be `None`")  # noqa: E501

        self._device_ssa = device_ssa

    @property
    def serial_number(self):
        """Gets the serial_number of this AllowHemsRequestBody.


        :return: The serial_number of this AllowHemsRequestBody.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this AllowHemsRequestBody.


        :param serial_number: The serial_number of this AllowHemsRequestBody.
        :type serial_number: str
        """
        if serial_number is None:
            raise ValueError("Invalid value for `serial_number`, must not be `None`")  # noqa: E501

        self._serial_number = serial_number

    @property
    def allow_hems(self):
        """Gets the allow_hems of this AllowHemsRequestBody.


        :return: The allow_hems of this AllowHemsRequestBody.
        :rtype: bool
        """
        return self._allow_hems

    @allow_hems.setter
    def allow_hems(self, allow_hems):
        """Sets the allow_hems of this AllowHemsRequestBody.


        :param allow_hems: The allow_hems of this AllowHemsRequestBody.
        :type allow_hems: bool
        """
        if allow_hems is None:
            raise ValueError("Invalid value for `allow_hems`, must not be `None`")  # noqa: E501

        self._allow_hems = allow_hems
