# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class ApplianceType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    WASHINGMACHINE = "WashingMachine"
    DISHWASHER = "Dishwasher"
    DRYER = "Dryer"
    def __init__(self):  # noqa: E501
        """ApplianceType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ApplianceType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApplianceType of this ApplianceType.  # noqa: E501
        :rtype: ApplianceType
        """
        return util.deserialize_model(dikt, cls)
