# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class AutomaticManagementResponseBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, automatic_management=None):  # noqa: E501
        """AutomaticManagementResponseBody - a model defined in OpenAPI

        :param automatic_management: The automatic_management of this AutomaticManagementResponseBody.  # noqa: E501
        :type automatic_management: bool
        """
        self.openapi_types = {
            'automatic_management': bool
        }

        self.attribute_map = {
            'automatic_management': 'automatic_management'
        }

        self._automatic_management = automatic_management

    @classmethod
    def from_dict(cls, dikt) -> 'AutomaticManagementResponseBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AutomaticManagementResponseBody of this AutomaticManagementResponseBody.  # noqa: E501
        :rtype: AutomaticManagementResponseBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def automatic_management(self):
        """Gets the automatic_management of this AutomaticManagementResponseBody.


        :return: The automatic_management of this AutomaticManagementResponseBody.
        :rtype: bool
        """
        return self._automatic_management

    @automatic_management.setter
    def automatic_management(self, automatic_management):
        """Sets the automatic_management of this AutomaticManagementResponseBody.


        :param automatic_management: The automatic_management of this AutomaticManagementResponseBody.
        :type automatic_management: bool
        """
        if automatic_management is None:
            raise ValueError("Invalid value for `automatic_management`, must not be `None`")  # noqa: E501

        self._automatic_management = automatic_management
