# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class DelaysList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, delays=None):  # noqa: E501
        """DelaysList - a model defined in OpenAPI

        :param delays: The delays of this DelaysList.  # noqa: E501
        :type delays: List[datetime]
        """
        self.openapi_types = {
            'delays': List[datetime]
        }

        self.attribute_map = {
            'delays': 'delays'
        }

        self._delays = delays

    @classmethod
    def from_dict(cls, dikt) -> 'DelaysList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DelaysList of this DelaysList.  # noqa: E501
        :rtype: DelaysList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def delays(self):
        """Gets the delays of this DelaysList.


        :return: The delays of this DelaysList.
        :rtype: List[datetime]
        """
        return self._delays

    @delays.setter
    def delays(self, delays):
        """Sets the delays of this DelaysList.


        :param delays: The delays of this DelaysList.
        :type delays: List[datetime]
        """
        if delays is None:
            raise ValueError("Invalid value for `delays`, must not be `None`")  # noqa: E501

        self._delays = delays
