# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class DelaysByCycleRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sequence_id=None, serial_number=None, new_start_time=None):  # noqa: E501
        """DelaysByCycleRequestBody - a model defined in OpenAPI

        :param sequence_id: The sequence_id of this DelaysByCycleRequestBody.  # noqa: E501
        :type sequence_id: str
        :param serial_number: The serial_number of this DelaysByCycleRequestBody.  # noqa: E501
        :type serial_number: str
        :param new_start_time: The new_start_time of this DelaysByCycleRequestBody.  # noqa: E501
        :type new_start_time: datetime
        """
        self.openapi_types = {
            'sequence_id': str,
            'serial_number': str,
            'new_start_time': datetime
        }

        self.attribute_map = {
            'sequence_id': 'sequence_id',
            'serial_number': 'serial_number',
            'new_start_time': 'new_start_time'
        }

        self._sequence_id = sequence_id
        self._serial_number = serial_number
        self._new_start_time = new_start_time

    @classmethod
    def from_dict(cls, dikt) -> 'DelaysByCycleRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DelaysByCycleRequestBody of this DelaysByCycleRequestBody.  # noqa: E501
        :rtype: DelaysByCycleRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sequence_id(self):
        """Gets the sequence_id of this DelaysByCycleRequestBody.


        :return: The sequence_id of this DelaysByCycleRequestBody.
        :rtype: str
        """
        return self._sequence_id

    @sequence_id.setter
    def sequence_id(self, sequence_id):
        """Sets the sequence_id of this DelaysByCycleRequestBody.


        :param sequence_id: The sequence_id of this DelaysByCycleRequestBody.
        :type sequence_id: str
        """
        if sequence_id is None:
            raise ValueError("Invalid value for `sequence_id`, must not be `None`")  # noqa: E501

        self._sequence_id = sequence_id

    @property
    def serial_number(self):
        """Gets the serial_number of this DelaysByCycleRequestBody.


        :return: The serial_number of this DelaysByCycleRequestBody.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this DelaysByCycleRequestBody.


        :param serial_number: The serial_number of this DelaysByCycleRequestBody.
        :type serial_number: str
        """
        if serial_number is None:
            raise ValueError("Invalid value for `serial_number`, must not be `None`")  # noqa: E501

        self._serial_number = serial_number

    @property
    def new_start_time(self):
        """Gets the new_start_time of this DelaysByCycleRequestBody.


        :return: The new_start_time of this DelaysByCycleRequestBody.
        :rtype: datetime
        """
        return self._new_start_time

    @new_start_time.setter
    def new_start_time(self, new_start_time):
        """Sets the new_start_time of this DelaysByCycleRequestBody.


        :param new_start_time: The new_start_time of this DelaysByCycleRequestBody.
        :type new_start_time: datetime
        """
        if new_start_time is None:
            raise ValueError("Invalid value for `new_start_time`, must not be `None`")  # noqa: E501

        self._new_start_time = new_start_time
