# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class DelaysStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sequence_id=None, serial_number=None, delayed=None, message=None):  # noqa: E501
        """DelaysStatus - a model defined in OpenAPI

        :param sequence_id: The sequence_id of this DelaysStatus.  # noqa: E501
        :type sequence_id: str
        :param serial_number: The serial_number of this DelaysStatus.  # noqa: E501
        :type serial_number: str
        :param delayed: The delayed of this DelaysStatus.  # noqa: E501
        :type delayed: bool
        :param message: The message of this DelaysStatus.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'sequence_id': str,
            'serial_number': str,
            'delayed': bool,
            'message': str
        }

        self.attribute_map = {
            'sequence_id': 'sequence_id',
            'serial_number': 'serial_number',
            'delayed': 'delayed',
            'message': 'message'
        }

        self._sequence_id = sequence_id
        self._serial_number = serial_number
        self._delayed = delayed
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'DelaysStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DelaysStatus of this DelaysStatus.  # noqa: E501
        :rtype: DelaysStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sequence_id(self):
        """Gets the sequence_id of this DelaysStatus.


        :return: The sequence_id of this DelaysStatus.
        :rtype: str
        """
        return self._sequence_id

    @sequence_id.setter
    def sequence_id(self, sequence_id):
        """Sets the sequence_id of this DelaysStatus.


        :param sequence_id: The sequence_id of this DelaysStatus.
        :type sequence_id: str
        """
        if sequence_id is None:
            raise ValueError("Invalid value for `sequence_id`, must not be `None`")  # noqa: E501

        self._sequence_id = sequence_id

    @property
    def serial_number(self):
        """Gets the serial_number of this DelaysStatus.


        :return: The serial_number of this DelaysStatus.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this DelaysStatus.


        :param serial_number: The serial_number of this DelaysStatus.
        :type serial_number: str
        """
        if serial_number is None:
            raise ValueError("Invalid value for `serial_number`, must not be `None`")  # noqa: E501

        self._serial_number = serial_number

    @property
    def delayed(self):
        """Gets the delayed of this DelaysStatus.


        :return: The delayed of this DelaysStatus.
        :rtype: bool
        """
        return self._delayed

    @delayed.setter
    def delayed(self, delayed):
        """Sets the delayed of this DelaysStatus.


        :param delayed: The delayed of this DelaysStatus.
        :type delayed: bool
        """
        if delayed is None:
            raise ValueError("Invalid value for `delayed`, must not be `None`")  # noqa: E501

        self._delayed = delayed

    @property
    def message(self):
        """Gets the message of this DelaysStatus.


        :return: The message of this DelaysStatus.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this DelaysStatus.


        :param message: The message of this DelaysStatus.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
