# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class DeleteType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SOFT = "soft"
    HARD = "hard"
    def __init__(self):  # noqa: E501
        """DeleteType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteType of this DeleteType.  # noqa: E501
        :rtype: DeleteType
        """
        return util.deserialize_model(dikt, cls)
