# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.not_disturb import NotDisturb
from device_manager_service.models.shiftable_machine import ShiftableMachine
from device_manager_service import util

from device_manager_service.models.not_disturb import NotDisturb  # noqa: E501
from device_manager_service.models.shiftable_machine import ShiftableMachine  # noqa: E501

class Device(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, serial_number=None, name=None, device_type=None, brand=None, allow_hems=None, automatic_management=None, device_ssa=None, not_disturb=None):  # noqa: E501
        """Device - a model defined in OpenAPI

        :param serial_number: The serial_number of this Device.  # noqa: E501
        :type serial_number: str
        :param name: The name of this Device.  # noqa: E501
        :type name: str
        :param device_type: The device_type of this Device.  # noqa: E501
        :type device_type: str
        :param brand: The brand of this Device.  # noqa: E501
        :type brand: str
        :param allow_hems: The allow_hems of this Device.  # noqa: E501
        :type allow_hems: bool
        :param automatic_management: The automatic_management of this Device.  # noqa: E501
        :type automatic_management: bool
        :param device_ssa: The device_ssa of this Device.  # noqa: E501
        :type device_ssa: str
        :param not_disturb: The not_disturb of this Device.  # noqa: E501
        :type not_disturb: NotDisturb
        """
        self.openapi_types = {
            'serial_number': str,
            'name': str,
            'device_type': str,
            'brand': str,
            'allow_hems': bool,
            'automatic_management': bool,
            'device_ssa': str,
            'not_disturb': NotDisturb
        }

        self.attribute_map = {
            'serial_number': 'serial_number',
            'name': 'name',
            'device_type': 'device_type',
            'brand': 'brand',
            'allow_hems': 'allow_hems',
            'automatic_management': 'automatic_management',
            'device_ssa': 'device_ssa',
            'not_disturb': 'not_disturb'
        }

        self._serial_number = serial_number
        self._name = name
        self._device_type = device_type
        self._brand = brand
        self._allow_hems = allow_hems
        self._automatic_management = automatic_management
        self._device_ssa = device_ssa
        self._not_disturb = not_disturb

    @classmethod
    def from_dict(cls, dikt) -> 'Device':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Device of this Device.  # noqa: E501
        :rtype: Device
        """
        return util.deserialize_model(dikt, cls)

    @property
    def serial_number(self):
        """Gets the serial_number of this Device.


        :return: The serial_number of this Device.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this Device.


        :param serial_number: The serial_number of this Device.
        :type serial_number: str
        """
        if serial_number is None:
            raise ValueError("Invalid value for `serial_number`, must not be `None`")  # noqa: E501

        self._serial_number = serial_number

    @property
    def name(self):
        """Gets the name of this Device.


        :return: The name of this Device.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Device.


        :param name: The name of this Device.
        :type name: str
        """

        self._name = name

    @property
    def device_type(self):
        """Gets the device_type of this Device.


        :return: The device_type of this Device.
        :rtype: str
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type):
        """Sets the device_type of this Device.


        :param device_type: The device_type of this Device.
        :type device_type: str
        """
        if device_type is None:
            raise ValueError("Invalid value for `device_type`, must not be `None`")  # noqa: E501

        self._device_type = device_type

    @property
    def brand(self):
        """Gets the brand of this Device.


        :return: The brand of this Device.
        :rtype: str
        """
        return self._brand

    @brand.setter
    def brand(self, brand):
        """Sets the brand of this Device.


        :param brand: The brand of this Device.
        :type brand: str
        """
        if brand is None:
            raise ValueError("Invalid value for `brand`, must not be `None`")  # noqa: E501

        self._brand = brand

    @property
    def allow_hems(self):
        """Gets the allow_hems of this Device.


        :return: The allow_hems of this Device.
        :rtype: bool
        """
        return self._allow_hems

    @allow_hems.setter
    def allow_hems(self, allow_hems):
        """Sets the allow_hems of this Device.


        :param allow_hems: The allow_hems of this Device.
        :type allow_hems: bool
        """
        if allow_hems is None:
            raise ValueError("Invalid value for `allow_hems`, must not be `None`")  # noqa: E501

        self._allow_hems = allow_hems

    @property
    def automatic_management(self):
        """Gets the automatic_management of this Device.


        :return: The automatic_management of this Device.
        :rtype: bool
        """
        return self._automatic_management

    @automatic_management.setter
    def automatic_management(self, automatic_management):
        """Sets the automatic_management of this Device.


        :param automatic_management: The automatic_management of this Device.
        :type automatic_management: bool
        """
        if automatic_management is None:
            raise ValueError("Invalid value for `automatic_management`, must not be `None`")  # noqa: E501

        self._automatic_management = automatic_management

    @property
    def device_ssa(self):
        """Gets the device_ssa of this Device.


        :return: The device_ssa of this Device.
        :rtype: str
        """
        return self._device_ssa

    @device_ssa.setter
    def device_ssa(self, device_ssa):
        """Sets the device_ssa of this Device.


        :param device_ssa: The device_ssa of this Device.
        :type device_ssa: str
        """

        self._device_ssa = device_ssa

    @property
    def not_disturb(self):
        """Gets the not_disturb of this Device.


        :return: The not_disturb of this Device.
        :rtype: NotDisturb
        """
        return self._not_disturb

    @not_disturb.setter
    def not_disturb(self, not_disturb):
        """Sets the not_disturb of this Device.


        :param not_disturb: The not_disturb of this Device.
        :type not_disturb: NotDisturb
        """
        if not_disturb is None:
            raise ValueError("Invalid value for `not_disturb`, must not be `None`")  # noqa: E501

        self._not_disturb = not_disturb
