# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.machine_cycle import MachineCycle
from device_manager_service import util

from device_manager_service.models.machine_cycle import MachineCycle  # noqa: E501

class MachineCycleByDevice(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, serial_number=None, cycles=None):  # noqa: E501
        """MachineCycleByDevice - a model defined in OpenAPI

        :param serial_number: The serial_number of this MachineCycleByDevice.  # noqa: E501
        :type serial_number: str
        :param cycles: The cycles of this MachineCycleByDevice.  # noqa: E501
        :type cycles: List[MachineCycle]
        """
        self.openapi_types = {
            'serial_number': str,
            'cycles': List[MachineCycle]
        }

        self.attribute_map = {
            'serial_number': 'serial_number',
            'cycles': 'cycles'
        }

        self._serial_number = serial_number
        self._cycles = cycles

    @classmethod
    def from_dict(cls, dikt) -> 'MachineCycleByDevice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineCycleByDevice of this MachineCycleByDevice.  # noqa: E501
        :rtype: MachineCycleByDevice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def serial_number(self):
        """Gets the serial_number of this MachineCycleByDevice.


        :return: The serial_number of this MachineCycleByDevice.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this MachineCycleByDevice.


        :param serial_number: The serial_number of this MachineCycleByDevice.
        :type serial_number: str
        """
        if serial_number is None:
            raise ValueError("Invalid value for `serial_number`, must not be `None`")  # noqa: E501

        self._serial_number = serial_number

    @property
    def cycles(self):
        """Gets the cycles of this MachineCycleByDevice.


        :return: The cycles of this MachineCycleByDevice.
        :rtype: List[MachineCycle]
        """
        return self._cycles

    @cycles.setter
    def cycles(self, cycles):
        """Sets the cycles of this MachineCycleByDevice.


        :param cycles: The cycles of this MachineCycleByDevice.
        :type cycles: List[MachineCycle]
        """
        if cycles is None:
            raise ValueError("Invalid value for `cycles`, must not be `None`")  # noqa: E501

        self._cycles = cycles
