# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.period_of_day import PeriodOfDay
from device_manager_service import util

from device_manager_service.models.period_of_day import PeriodOfDay  # noqa: E501

class NotDisturb(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sunday=None, monday=None, tuesday=None, wednesday=None, thursday=None, friday=None, saturday=None):  # noqa: E501
        """NotDisturb - a model defined in OpenAPI

        :param sunday: The sunday of this NotDisturb.  # noqa: E501
        :type sunday: List[PeriodOfDay]
        :param monday: The monday of this NotDisturb.  # noqa: E501
        :type monday: List[PeriodOfDay]
        :param tuesday: The tuesday of this NotDisturb.  # noqa: E501
        :type tuesday: List[PeriodOfDay]
        :param wednesday: The wednesday of this NotDisturb.  # noqa: E501
        :type wednesday: List[PeriodOfDay]
        :param thursday: The thursday of this NotDisturb.  # noqa: E501
        :type thursday: List[PeriodOfDay]
        :param friday: The friday of this NotDisturb.  # noqa: E501
        :type friday: List[PeriodOfDay]
        :param saturday: The saturday of this NotDisturb.  # noqa: E501
        :type saturday: List[PeriodOfDay]
        """
        self.openapi_types = {
            'sunday': List[PeriodOfDay],
            'monday': List[PeriodOfDay],
            'tuesday': List[PeriodOfDay],
            'wednesday': List[PeriodOfDay],
            'thursday': List[PeriodOfDay],
            'friday': List[PeriodOfDay],
            'saturday': List[PeriodOfDay]
        }

        self.attribute_map = {
            'sunday': 'sunday',
            'monday': 'monday',
            'tuesday': 'tuesday',
            'wednesday': 'wednesday',
            'thursday': 'thursday',
            'friday': 'friday',
            'saturday': 'saturday'
        }

        self._sunday = sunday
        self._monday = monday
        self._tuesday = tuesday
        self._wednesday = wednesday
        self._thursday = thursday
        self._friday = friday
        self._saturday = saturday

    @classmethod
    def from_dict(cls, dikt) -> 'NotDisturb':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NotDisturb of this NotDisturb.  # noqa: E501
        :rtype: NotDisturb
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sunday(self):
        """Gets the sunday of this NotDisturb.


        :return: The sunday of this NotDisturb.
        :rtype: List[PeriodOfDay]
        """
        return self._sunday

    @sunday.setter
    def sunday(self, sunday):
        """Sets the sunday of this NotDisturb.


        :param sunday: The sunday of this NotDisturb.
        :type sunday: List[PeriodOfDay]
        """

        self._sunday = sunday

    @property
    def monday(self):
        """Gets the monday of this NotDisturb.


        :return: The monday of this NotDisturb.
        :rtype: List[PeriodOfDay]
        """
        return self._monday

    @monday.setter
    def monday(self, monday):
        """Sets the monday of this NotDisturb.


        :param monday: The monday of this NotDisturb.
        :type monday: List[PeriodOfDay]
        """

        self._monday = monday

    @property
    def tuesday(self):
        """Gets the tuesday of this NotDisturb.


        :return: The tuesday of this NotDisturb.
        :rtype: List[PeriodOfDay]
        """
        return self._tuesday

    @tuesday.setter
    def tuesday(self, tuesday):
        """Sets the tuesday of this NotDisturb.


        :param tuesday: The tuesday of this NotDisturb.
        :type tuesday: List[PeriodOfDay]
        """

        self._tuesday = tuesday

    @property
    def wednesday(self):
        """Gets the wednesday of this NotDisturb.


        :return: The wednesday of this NotDisturb.
        :rtype: List[PeriodOfDay]
        """
        return self._wednesday

    @wednesday.setter
    def wednesday(self, wednesday):
        """Sets the wednesday of this NotDisturb.


        :param wednesday: The wednesday of this NotDisturb.
        :type wednesday: List[PeriodOfDay]
        """

        self._wednesday = wednesday

    @property
    def thursday(self):
        """Gets the thursday of this NotDisturb.


        :return: The thursday of this NotDisturb.
        :rtype: List[PeriodOfDay]
        """
        return self._thursday

    @thursday.setter
    def thursday(self, thursday):
        """Sets the thursday of this NotDisturb.


        :param thursday: The thursday of this NotDisturb.
        :type thursday: List[PeriodOfDay]
        """

        self._thursday = thursday

    @property
    def friday(self):
        """Gets the friday of this NotDisturb.


        :return: The friday of this NotDisturb.
        :rtype: List[PeriodOfDay]
        """
        return self._friday

    @friday.setter
    def friday(self, friday):
        """Sets the friday of this NotDisturb.


        :param friday: The friday of this NotDisturb.
        :type friday: List[PeriodOfDay]
        """

        self._friday = friday

    @property
    def saturday(self):
        """Gets the saturday of this NotDisturb.


        :return: The saturday of this NotDisturb.
        :rtype: List[PeriodOfDay]
        """
        return self._saturday

    @saturday.setter
    def saturday(self, saturday):
        """Sets the saturday of this NotDisturb.


        :param saturday: The saturday of this NotDisturb.
        :type saturday: List[PeriodOfDay]
        """

        self._saturday = saturday
