# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class Optimized(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    TRUE = "true"
    FALSE = "false"
    def __init__(self):  # noqa: E501
        """Optimized - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'Optimized':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Optimized of this Optimized.  # noqa: E501
        :rtype: Optimized
        """
        return util.deserialize_model(dikt, cls)
