# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class PeriodOfDay(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start_timestamp=None, end_timestamp=None):  # noqa: E501
        """PeriodOfDay - a model defined in OpenAPI

        :param start_timestamp: The start_timestamp of this PeriodOfDay.  # noqa: E501
        :type start_timestamp: datetime
        :param end_timestamp: The end_timestamp of this PeriodOfDay.  # noqa: E501
        :type end_timestamp: datetime
        """
        self.openapi_types = {
            'start_timestamp': datetime,
            'end_timestamp': datetime
        }

        self.attribute_map = {
            'start_timestamp': 'start_timestamp',
            'end_timestamp': 'end_timestamp'
        }

        self._start_timestamp = start_timestamp
        self._end_timestamp = end_timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'PeriodOfDay':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PeriodOfDay of this PeriodOfDay.  # noqa: E501
        :rtype: PeriodOfDay
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_timestamp(self):
        """Gets the start_timestamp of this PeriodOfDay.


        :return: The start_timestamp of this PeriodOfDay.
        :rtype: datetime
        """
        return self._start_timestamp

    @start_timestamp.setter
    def start_timestamp(self, start_timestamp):
        """Sets the start_timestamp of this PeriodOfDay.


        :param start_timestamp: The start_timestamp of this PeriodOfDay.
        :type start_timestamp: datetime
        """
        if start_timestamp is None:
            raise ValueError("Invalid value for `start_timestamp`, must not be `None`")  # noqa: E501

        self._start_timestamp = start_timestamp

    @property
    def end_timestamp(self):
        """Gets the end_timestamp of this PeriodOfDay.


        :return: The end_timestamp of this PeriodOfDay.
        :rtype: datetime
        """
        return self._end_timestamp

    @end_timestamp.setter
    def end_timestamp(self, end_timestamp):
        """Sets the end_timestamp of this PeriodOfDay.


        :param end_timestamp: The end_timestamp of this PeriodOfDay.
        :type end_timestamp: datetime
        """
        if end_timestamp is None:
            raise ValueError("Invalid value for `end_timestamp`, must not be `None`")  # noqa: E501

        self._end_timestamp = end_timestamp
