# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.machine_cycle import MachineCycle
from device_manager_service import util

from device_manager_service.models.machine_cycle import MachineCycle  # noqa: E501

class Pool(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, serial_number=None, device_type=None, cycles_in_pool=None):  # noqa: E501
        """Pool - a model defined in OpenAPI

        :param serial_number: The serial_number of this Pool.  # noqa: E501
        :type serial_number: str
        :param device_type: The device_type of this Pool.  # noqa: E501
        :type device_type: str
        :param cycles_in_pool: The cycles_in_pool of this Pool.  # noqa: E501
        :type cycles_in_pool: List[MachineCycle]
        """
        self.openapi_types = {
            'serial_number': str,
            'device_type': str,
            'cycles_in_pool': List[MachineCycle]
        }

        self.attribute_map = {
            'serial_number': 'serial_number',
            'device_type': 'device_type',
            'cycles_in_pool': 'cycles_in_pool'
        }

        self._serial_number = serial_number
        self._device_type = device_type
        self._cycles_in_pool = cycles_in_pool

    @classmethod
    def from_dict(cls, dikt) -> 'Pool':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pool of this Pool.  # noqa: E501
        :rtype: Pool
        """
        return util.deserialize_model(dikt, cls)

    @property
    def serial_number(self):
        """Gets the serial_number of this Pool.


        :return: The serial_number of this Pool.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this Pool.


        :param serial_number: The serial_number of this Pool.
        :type serial_number: str
        """
        if serial_number is None:
            raise ValueError("Invalid value for `serial_number`, must not be `None`")  # noqa: E501

        self._serial_number = serial_number

    @property
    def device_type(self):
        """Gets the device_type of this Pool.


        :return: The device_type of this Pool.
        :rtype: str
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type):
        """Sets the device_type of this Pool.


        :param device_type: The device_type of this Pool.
        :type device_type: str
        """

        self._device_type = device_type

    @property
    def cycles_in_pool(self):
        """Gets the cycles_in_pool of this Pool.


        :return: The cycles_in_pool of this Pool.
        :rtype: List[MachineCycle]
        """
        return self._cycles_in_pool

    @cycles_in_pool.setter
    def cycles_in_pool(self, cycles_in_pool):
        """Sets the cycles_in_pool of this Pool.


        :param cycles_in_pool: The cycles_in_pool of this Pool.
        :type cycles_in_pool: List[MachineCycle]
        """
        if cycles_in_pool is None:
            raise ValueError("Invalid value for `cycles_in_pool`, must not be `None`")  # noqa: E501

        self._cycles_in_pool = cycles_in_pool
