# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.pool import Pool
from device_manager_service import util

from device_manager_service.models.pool import Pool  # noqa: E501

class PoolByUser(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, pool=None):  # noqa: E501
        """PoolByUser - a model defined in OpenAPI

        :param user_id: The user_id of this PoolByUser.  # noqa: E501
        :type user_id: str
        :param pool: The pool of this PoolByUser.  # noqa: E501
        :type pool: List[Pool]
        """
        self.openapi_types = {
            'user_id': str,
            'pool': List[Pool]
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'pool': 'pool'
        }

        self._user_id = user_id
        self._pool = pool

    @classmethod
    def from_dict(cls, dikt) -> 'PoolByUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PoolByUser of this PoolByUser.  # noqa: E501
        :rtype: PoolByUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this PoolByUser.


        :return: The user_id of this PoolByUser.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this PoolByUser.


        :param user_id: The user_id of this PoolByUser.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501
        if user_id is not None and len(user_id) > 10:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `10`")  # noqa: E501
        if user_id is not None and len(user_id) < 10:
            raise ValueError("Invalid value for `user_id`, length must be greater than or equal to `10`")  # noqa: E501

        self._user_id = user_id

    @property
    def pool(self):
        """Gets the pool of this PoolByUser.


        :return: The pool of this PoolByUser.
        :rtype: List[Pool]
        """
        return self._pool

    @pool.setter
    def pool(self, pool):
        """Sets the pool of this PoolByUser.


        :param pool: The pool of this PoolByUser.
        :type pool: List[Pool]
        """
        if pool is None:
            raise ValueError("Invalid value for `pool`, must not be `None`")  # noqa: E501

        self._pool = pool
