# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.pool import Pool
from device_manager_service import util

from device_manager_service.models.pool import Pool  # noqa: E501

class PoolByDevice(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pool=None):  # noqa: E501
        """PoolByDevice - a model defined in OpenAPI

        :param pool: The pool of this PoolByDevice.  # noqa: E501
        :type pool: List[Pool]
        """
        self.openapi_types = {
            'pool': List[Pool]
        }

        self.attribute_map = {
            'pool': 'pool'
        }

        self._pool = pool

    @classmethod
    def from_dict(cls, dikt) -> 'PoolByDevice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PoolByDevice of this PoolByDevice.  # noqa: E501
        :rtype: PoolByDevice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pool(self):
        """Gets the pool of this PoolByDevice.


        :return: The pool of this PoolByDevice.
        :rtype: List[Pool]
        """
        return self._pool

    @pool.setter
    def pool(self, pool):
        """Sets the pool of this PoolByDevice.


        :param pool: The pool of this PoolByDevice.
        :type pool: List[Pool]
        """
        if pool is None:
            raise ValueError("Invalid value for `pool`, must not be `None`")  # noqa: E501

        self._pool = pool
