# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.power_units import PowerUnits
from device_manager_service import util

from device_manager_service.models.power_units import PowerUnits  # noqa: E501

class PowerProfile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, slot=None, max_power=None, min_power=None, expected_power=None, power_units=None, duration=None, duration_units=None):  # noqa: E501
        """PowerProfile - a model defined in OpenAPI

        :param slot: The slot of this PowerProfile.  # noqa: E501
        :type slot: int
        :param max_power: The max_power of this PowerProfile.  # noqa: E501
        :type max_power: float
        :param min_power: The min_power of this PowerProfile.  # noqa: E501
        :type min_power: float
        :param expected_power: The expected_power of this PowerProfile.  # noqa: E501
        :type expected_power: float
        :param power_units: The power_units of this PowerProfile.  # noqa: E501
        :type power_units: PowerUnits
        :param duration: The duration of this PowerProfile.  # noqa: E501
        :type duration: float
        :param duration_units: The duration_units of this PowerProfile.  # noqa: E501
        :type duration_units: str
        """
        self.openapi_types = {
            'slot': int,
            'max_power': float,
            'min_power': float,
            'expected_power': float,
            'power_units': PowerUnits,
            'duration': float,
            'duration_units': str
        }

        self.attribute_map = {
            'slot': 'slot',
            'max_power': 'max_power',
            'min_power': 'min_power',
            'expected_power': 'expected_power',
            'power_units': 'power_units',
            'duration': 'duration',
            'duration_units': 'duration_units'
        }

        self._slot = slot
        self._max_power = max_power
        self._min_power = min_power
        self._expected_power = expected_power
        self._power_units = power_units
        self._duration = duration
        self._duration_units = duration_units

    @classmethod
    def from_dict(cls, dikt) -> 'PowerProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PowerProfile of this PowerProfile.  # noqa: E501
        :rtype: PowerProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def slot(self):
        """Gets the slot of this PowerProfile.


        :return: The slot of this PowerProfile.
        :rtype: int
        """
        return self._slot

    @slot.setter
    def slot(self, slot):
        """Sets the slot of this PowerProfile.


        :param slot: The slot of this PowerProfile.
        :type slot: int
        """
        if slot is None:
            raise ValueError("Invalid value for `slot`, must not be `None`")  # noqa: E501

        self._slot = slot

    @property
    def max_power(self):
        """Gets the max_power of this PowerProfile.


        :return: The max_power of this PowerProfile.
        :rtype: float
        """
        return self._max_power

    @max_power.setter
    def max_power(self, max_power):
        """Sets the max_power of this PowerProfile.


        :param max_power: The max_power of this PowerProfile.
        :type max_power: float
        """
        if max_power is None:
            raise ValueError("Invalid value for `max_power`, must not be `None`")  # noqa: E501
        if max_power is not None and max_power < 0:  # noqa: E501
            raise ValueError("Invalid value for `max_power`, must be a value greater than or equal to `0`")  # noqa: E501

        self._max_power = max_power

    @property
    def min_power(self):
        """Gets the min_power of this PowerProfile.


        :return: The min_power of this PowerProfile.
        :rtype: float
        """
        return self._min_power

    @min_power.setter
    def min_power(self, min_power):
        """Sets the min_power of this PowerProfile.


        :param min_power: The min_power of this PowerProfile.
        :type min_power: float
        """
        if min_power is not None and min_power < 0:  # noqa: E501
            raise ValueError("Invalid value for `min_power`, must be a value greater than or equal to `0`")  # noqa: E501

        self._min_power = min_power

    @property
    def expected_power(self):
        """Gets the expected_power of this PowerProfile.


        :return: The expected_power of this PowerProfile.
        :rtype: float
        """
        return self._expected_power

    @expected_power.setter
    def expected_power(self, expected_power):
        """Sets the expected_power of this PowerProfile.


        :param expected_power: The expected_power of this PowerProfile.
        :type expected_power: float
        """
        if expected_power is not None and expected_power < 0:  # noqa: E501
            raise ValueError("Invalid value for `expected_power`, must be a value greater than or equal to `0`")  # noqa: E501

        self._expected_power = expected_power

    @property
    def power_units(self):
        """Gets the power_units of this PowerProfile.


        :return: The power_units of this PowerProfile.
        :rtype: PowerUnits
        """
        return self._power_units

    @power_units.setter
    def power_units(self, power_units):
        """Sets the power_units of this PowerProfile.


        :param power_units: The power_units of this PowerProfile.
        :type power_units: PowerUnits
        """
        if power_units is None:
            raise ValueError("Invalid value for `power_units`, must not be `None`")  # noqa: E501

        self._power_units = power_units

    @property
    def duration(self):
        """Gets the duration of this PowerProfile.


        :return: The duration of this PowerProfile.
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this PowerProfile.


        :param duration: The duration of this PowerProfile.
        :type duration: float
        """
        if duration is None:
            raise ValueError("Invalid value for `duration`, must not be `None`")  # noqa: E501
        if duration is not None and duration < 0:  # noqa: E501
            raise ValueError("Invalid value for `duration`, must be a value greater than or equal to `0`")  # noqa: E501

        self._duration = duration

    @property
    def duration_units(self):
        """Gets the duration_units of this PowerProfile.


        :return: The duration_units of this PowerProfile.
        :rtype: str
        """
        return self._duration_units

    @duration_units.setter
    def duration_units(self, duration_units):
        """Sets the duration_units of this PowerProfile.


        :param duration_units: The duration_units of this PowerProfile.
        :type duration_units: str
        """
        allowed_values = ["minutes"]  # noqa: E501
        if duration_units not in allowed_values:
            raise ValueError(
                "Invalid value for `duration_units` ({0}), must be one of {1}"
                .format(duration_units, allowed_values)
            )

        self._duration_units = duration_units
