# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.power_units import PowerUnits
from device_manager_service import util

from device_manager_service.models.power_units import PowerUnits  # noqa: E501

class PowerRating(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None, units=None):  # noqa: E501
        """PowerRating - a model defined in OpenAPI

        :param value: The value of this PowerRating.  # noqa: E501
        :type value: int
        :param units: The units of this PowerRating.  # noqa: E501
        :type units: PowerUnits
        """
        self.openapi_types = {
            'value': int,
            'units': PowerUnits
        }

        self.attribute_map = {
            'value': 'value',
            'units': 'units'
        }

        self._value = value
        self._units = units

    @classmethod
    def from_dict(cls, dikt) -> 'PowerRating':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PowerRating of this PowerRating.  # noqa: E501
        :rtype: PowerRating
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self):
        """Gets the value of this PowerRating.


        :return: The value of this PowerRating.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this PowerRating.


        :param value: The value of this PowerRating.
        :type value: int
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501
        if value is not None and value < 0:  # noqa: E501
            raise ValueError("Invalid value for `value`, must be a value greater than or equal to `0`")  # noqa: E501

        self._value = value

    @property
    def units(self):
        """Gets the units of this PowerRating.


        :return: The units of this PowerRating.
        :rtype: PowerUnits
        """
        return self._units

    @units.setter
    def units(self, units):
        """Sets the units of this PowerRating.


        :param units: The units of this PowerRating.
        :type units: PowerUnits
        """
        if units is None:
            raise ValueError("Invalid value for `units`, must not be `None`")  # noqa: E501

        self._units = units
