# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class RemoveDeviceRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, serial_number=None):  # noqa: E501
        """RemoveDeviceRequestBody - a model defined in OpenAPI

        :param serial_number: The serial_number of this RemoveDeviceRequestBody.  # noqa: E501
        :type serial_number: str
        """
        self.openapi_types = {
            'serial_number': str
        }

        self.attribute_map = {
            'serial_number': 'serial_number'
        }

        self._serial_number = serial_number

    @classmethod
    def from_dict(cls, dikt) -> 'RemoveDeviceRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RemoveDeviceRequestBody of this RemoveDeviceRequestBody.  # noqa: E501
        :rtype: RemoveDeviceRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def serial_number(self):
        """Gets the serial_number of this RemoveDeviceRequestBody.


        :return: The serial_number of this RemoveDeviceRequestBody.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this RemoveDeviceRequestBody.


        :param serial_number: The serial_number of this RemoveDeviceRequestBody.
        :type serial_number: str
        """
        if serial_number is None:
            raise ValueError("Invalid value for `serial_number`, must not be `None`")  # noqa: E501

        self._serial_number = serial_number
