# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class ScheduleCycleRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, scheduled_start_time=None, program=None):  # noqa: E501
        """ScheduleCycleRequestBody - a model defined in OpenAPI

        :param scheduled_start_time: The scheduled_start_time of this ScheduleCycleRequestBody.  # noqa: E501
        :type scheduled_start_time: datetime
        :param program: The program of this ScheduleCycleRequestBody.  # noqa: E501
        :type program: str
        """
        self.openapi_types = {
            'scheduled_start_time': datetime,
            'program': str
        }

        self.attribute_map = {
            'scheduled_start_time': 'scheduled_start_time',
            'program': 'program'
        }

        self._scheduled_start_time = scheduled_start_time
        self._program = program

    @classmethod
    def from_dict(cls, dikt) -> 'ScheduleCycleRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScheduleCycleRequestBody of this ScheduleCycleRequestBody.  # noqa: E501
        :rtype: ScheduleCycleRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def scheduled_start_time(self):
        """Gets the scheduled_start_time of this ScheduleCycleRequestBody.


        :return: The scheduled_start_time of this ScheduleCycleRequestBody.
        :rtype: datetime
        """
        return self._scheduled_start_time

    @scheduled_start_time.setter
    def scheduled_start_time(self, scheduled_start_time):
        """Sets the scheduled_start_time of this ScheduleCycleRequestBody.


        :param scheduled_start_time: The scheduled_start_time of this ScheduleCycleRequestBody.
        :type scheduled_start_time: datetime
        """
        if scheduled_start_time is None:
            raise ValueError("Invalid value for `scheduled_start_time`, must not be `None`")  # noqa: E501

        self._scheduled_start_time = scheduled_start_time

    @property
    def program(self):
        """Gets the program of this ScheduleCycleRequestBody.


        :return: The program of this ScheduleCycleRequestBody.
        :rtype: str
        """
        return self._program

    @program.setter
    def program(self, program):
        """Sets the program of this ScheduleCycleRequestBody.


        :param program: The program of this ScheduleCycleRequestBody.
        :type program: str
        """
        if program is None:
            raise ValueError("Invalid value for `program`, must not be `None`")  # noqa: E501

        self._program = program
