# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.settings import Settings
from device_manager_service import util

from device_manager_service.models.settings import Settings  # noqa: E501

class SettingsByUser(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, settings=None):  # noqa: E501
        """SettingsByUser - a model defined in OpenAPI

        :param user_id: The user_id of this SettingsByUser.  # noqa: E501
        :type user_id: str
        :param settings: The settings of this SettingsByUser.  # noqa: E501
        :type settings: List[Settings]
        """
        self.openapi_types = {
            'user_id': str,
            'settings': List[Settings]
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'settings': 'settings'
        }

        self._user_id = user_id
        self._settings = settings

    @classmethod
    def from_dict(cls, dikt) -> 'SettingsByUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SettingsByUser of this SettingsByUser.  # noqa: E501
        :rtype: SettingsByUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this SettingsByUser.


        :return: The user_id of this SettingsByUser.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this SettingsByUser.


        :param user_id: The user_id of this SettingsByUser.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501
        if user_id is not None and len(user_id) > 10:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `10`")  # noqa: E501
        if user_id is not None and len(user_id) < 10:
            raise ValueError("Invalid value for `user_id`, length must be greater than or equal to `10`")  # noqa: E501

        self._user_id = user_id

    @property
    def settings(self):
        """Gets the settings of this SettingsByUser.


        :return: The settings of this SettingsByUser.
        :rtype: List[Settings]
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this SettingsByUser.


        :param settings: The settings of this SettingsByUser.
        :type settings: List[Settings]
        """
        if settings is None:
            raise ValueError("Invalid value for `settings`, must not be `None`")  # noqa: E501

        self._settings = settings
