# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.settings import Settings
from device_manager_service import util

from device_manager_service.models.settings import Settings  # noqa: E501

class SettingsByDevice(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, settings=None):  # noqa: E501
        """SettingsByDevice - a model defined in OpenAPI

        :param settings: The settings of this SettingsByDevice.  # noqa: E501
        :type settings: List[Settings]
        """
        self.openapi_types = {
            'settings': List[Settings]
        }

        self.attribute_map = {
            'settings': 'settings'
        }

        self._settings = settings

    @classmethod
    def from_dict(cls, dikt) -> 'SettingsByDevice':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SettingsByDevice of this SettingsByDevice.  # noqa: E501
        :rtype: SettingsByDevice
        """
        return util.deserialize_model(dikt, cls)

    @property
    def settings(self):
        """Gets the settings of this SettingsByDevice.


        :return: The settings of this SettingsByDevice.
        :rtype: List[Settings]
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this SettingsByDevice.


        :param settings: The settings of this SettingsByDevice.
        :type settings: List[Settings]
        """
        if settings is None:
            raise ValueError("Invalid value for `settings`, must not be `None`")  # noqa: E501

        self._settings = settings
