# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.not_disturb import NotDisturb
from device_manager_service.models.shiftable_machine_settings import ShiftableMachineSettings
from device_manager_service import util

from device_manager_service.models.not_disturb import NotDisturb  # noqa: E501
from device_manager_service.models.shiftable_machine_settings import ShiftableMachineSettings  # noqa: E501

class Settings(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, serial_number=None, not_disturb=None, allow_hems=None, automatic_management=None):  # noqa: E501
        """Settings - a model defined in OpenAPI

        :param serial_number: The serial_number of this Settings.  # noqa: E501
        :type serial_number: str
        :param not_disturb: The not_disturb of this Settings.  # noqa: E501
        :type not_disturb: NotDisturb
        :param allow_hems: The allow_hems of this Settings.  # noqa: E501
        :type allow_hems: bool
        :param automatic_management: The automatic_management of this Settings.  # noqa: E501
        :type automatic_management: bool
        """
        self.openapi_types = {
            'serial_number': str,
            'not_disturb': NotDisturb,
            'allow_hems': bool,
            'automatic_management': bool
        }

        self.attribute_map = {
            'serial_number': 'serial_number',
            'not_disturb': 'not_disturb',
            'allow_hems': 'allow_hems',
            'automatic_management': 'automatic_management'
        }

        self._serial_number = serial_number
        self._not_disturb = not_disturb
        self._allow_hems = allow_hems
        self._automatic_management = automatic_management

    @classmethod
    def from_dict(cls, dikt) -> 'Settings':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Settings of this Settings.  # noqa: E501
        :rtype: Settings
        """
        return util.deserialize_model(dikt, cls)

    @property
    def serial_number(self):
        """Gets the serial_number of this Settings.


        :return: The serial_number of this Settings.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this Settings.


        :param serial_number: The serial_number of this Settings.
        :type serial_number: str
        """
        if serial_number is None:
            raise ValueError("Invalid value for `serial_number`, must not be `None`")  # noqa: E501

        self._serial_number = serial_number

    @property
    def not_disturb(self):
        """Gets the not_disturb of this Settings.


        :return: The not_disturb of this Settings.
        :rtype: NotDisturb
        """
        return self._not_disturb

    @not_disturb.setter
    def not_disturb(self, not_disturb):
        """Sets the not_disturb of this Settings.


        :param not_disturb: The not_disturb of this Settings.
        :type not_disturb: NotDisturb
        """
        if not_disturb is None:
            raise ValueError("Invalid value for `not_disturb`, must not be `None`")  # noqa: E501

        self._not_disturb = not_disturb

    @property
    def allow_hems(self):
        """Gets the allow_hems of this Settings.


        :return: The allow_hems of this Settings.
        :rtype: bool
        """
        return self._allow_hems

    @allow_hems.setter
    def allow_hems(self, allow_hems):
        """Sets the allow_hems of this Settings.


        :param allow_hems: The allow_hems of this Settings.
        :type allow_hems: bool
        """
        if allow_hems is None:
            raise ValueError("Invalid value for `allow_hems`, must not be `None`")  # noqa: E501

        self._allow_hems = allow_hems

    @property
    def automatic_management(self):
        """Gets the automatic_management of this Settings.


        :return: The automatic_management of this Settings.
        :rtype: bool
        """
        return self._automatic_management

    @automatic_management.setter
    def automatic_management(self, automatic_management):
        """Sets the automatic_management of this Settings.


        :param automatic_management: The automatic_management of this Settings.
        :type automatic_management: bool
        """
        if automatic_management is None:
            raise ValueError("Invalid value for `automatic_management`, must not be `None`")  # noqa: E501

        self._automatic_management = automatic_management
