# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.power_profile import PowerProfile
from device_manager_service import util

from device_manager_service.models.power_profile import PowerProfile  # noqa: E501

class ShiftableMachineCycle(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sequence_id=None, earliest_start_time=None, latest_end_time=None, scheduled_start_time=None, expected_end_time=None, program=None, is_optimized=None, power_profile=None):  # noqa: E501
        """ShiftableMachineCycle - a model defined in OpenAPI

        :param sequence_id: The sequence_id of this ShiftableMachineCycle.  # noqa: E501
        :type sequence_id: str
        :param earliest_start_time: The earliest_start_time of this ShiftableMachineCycle.  # noqa: E501
        :type earliest_start_time: datetime
        :param latest_end_time: The latest_end_time of this ShiftableMachineCycle.  # noqa: E501
        :type latest_end_time: datetime
        :param scheduled_start_time: The scheduled_start_time of this ShiftableMachineCycle.  # noqa: E501
        :type scheduled_start_time: datetime
        :param expected_end_time: The expected_end_time of this ShiftableMachineCycle.  # noqa: E501
        :type expected_end_time: datetime
        :param program: The program of this ShiftableMachineCycle.  # noqa: E501
        :type program: str
        :param is_optimized: The is_optimized of this ShiftableMachineCycle.  # noqa: E501
        :type is_optimized: bool
        :param power_profile: The power_profile of this ShiftableMachineCycle.  # noqa: E501
        :type power_profile: List[PowerProfile]
        """
        self.openapi_types = {
            'sequence_id': str,
            'earliest_start_time': datetime,
            'latest_end_time': datetime,
            'scheduled_start_time': datetime,
            'expected_end_time': datetime,
            'program': str,
            'is_optimized': bool,
            'power_profile': List[PowerProfile]
        }

        self.attribute_map = {
            'sequence_id': 'sequence_id',
            'earliest_start_time': 'earliest_start_time',
            'latest_end_time': 'latest_end_time',
            'scheduled_start_time': 'scheduled_start_time',
            'expected_end_time': 'expected_end_time',
            'program': 'program',
            'is_optimized': 'is_optimized',
            'power_profile': 'power_profile'
        }

        self._sequence_id = sequence_id
        self._earliest_start_time = earliest_start_time
        self._latest_end_time = latest_end_time
        self._scheduled_start_time = scheduled_start_time
        self._expected_end_time = expected_end_time
        self._program = program
        self._is_optimized = is_optimized
        self._power_profile = power_profile

    @classmethod
    def from_dict(cls, dikt) -> 'ShiftableMachineCycle':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ShiftableMachineCycle of this ShiftableMachineCycle.  # noqa: E501
        :rtype: ShiftableMachineCycle
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sequence_id(self):
        """Gets the sequence_id of this ShiftableMachineCycle.


        :return: The sequence_id of this ShiftableMachineCycle.
        :rtype: str
        """
        return self._sequence_id

    @sequence_id.setter
    def sequence_id(self, sequence_id):
        """Sets the sequence_id of this ShiftableMachineCycle.


        :param sequence_id: The sequence_id of this ShiftableMachineCycle.
        :type sequence_id: str
        """
        if sequence_id is None:
            raise ValueError("Invalid value for `sequence_id`, must not be `None`")  # noqa: E501

        self._sequence_id = sequence_id

    @property
    def earliest_start_time(self):
        """Gets the earliest_start_time of this ShiftableMachineCycle.


        :return: The earliest_start_time of this ShiftableMachineCycle.
        :rtype: datetime
        """
        return self._earliest_start_time

    @earliest_start_time.setter
    def earliest_start_time(self, earliest_start_time):
        """Sets the earliest_start_time of this ShiftableMachineCycle.


        :param earliest_start_time: The earliest_start_time of this ShiftableMachineCycle.
        :type earliest_start_time: datetime
        """

        self._earliest_start_time = earliest_start_time

    @property
    def latest_end_time(self):
        """Gets the latest_end_time of this ShiftableMachineCycle.


        :return: The latest_end_time of this ShiftableMachineCycle.
        :rtype: datetime
        """
        return self._latest_end_time

    @latest_end_time.setter
    def latest_end_time(self, latest_end_time):
        """Sets the latest_end_time of this ShiftableMachineCycle.


        :param latest_end_time: The latest_end_time of this ShiftableMachineCycle.
        :type latest_end_time: datetime
        """

        self._latest_end_time = latest_end_time

    @property
    def scheduled_start_time(self):
        """Gets the scheduled_start_time of this ShiftableMachineCycle.


        :return: The scheduled_start_time of this ShiftableMachineCycle.
        :rtype: datetime
        """
        return self._scheduled_start_time

    @scheduled_start_time.setter
    def scheduled_start_time(self, scheduled_start_time):
        """Sets the scheduled_start_time of this ShiftableMachineCycle.


        :param scheduled_start_time: The scheduled_start_time of this ShiftableMachineCycle.
        :type scheduled_start_time: datetime
        """
        if scheduled_start_time is None:
            raise ValueError("Invalid value for `scheduled_start_time`, must not be `None`")  # noqa: E501

        self._scheduled_start_time = scheduled_start_time

    @property
    def expected_end_time(self):
        """Gets the expected_end_time of this ShiftableMachineCycle.


        :return: The expected_end_time of this ShiftableMachineCycle.
        :rtype: datetime
        """
        return self._expected_end_time

    @expected_end_time.setter
    def expected_end_time(self, expected_end_time):
        """Sets the expected_end_time of this ShiftableMachineCycle.


        :param expected_end_time: The expected_end_time of this ShiftableMachineCycle.
        :type expected_end_time: datetime
        """
        if expected_end_time is None:
            raise ValueError("Invalid value for `expected_end_time`, must not be `None`")  # noqa: E501

        self._expected_end_time = expected_end_time

    @property
    def program(self):
        """Gets the program of this ShiftableMachineCycle.


        :return: The program of this ShiftableMachineCycle.
        :rtype: str
        """
        return self._program

    @program.setter
    def program(self, program):
        """Sets the program of this ShiftableMachineCycle.


        :param program: The program of this ShiftableMachineCycle.
        :type program: str
        """
        if program is None:
            raise ValueError("Invalid value for `program`, must not be `None`")  # noqa: E501

        self._program = program

    @property
    def is_optimized(self):
        """Gets the is_optimized of this ShiftableMachineCycle.


        :return: The is_optimized of this ShiftableMachineCycle.
        :rtype: bool
        """
        return self._is_optimized

    @is_optimized.setter
    def is_optimized(self, is_optimized):
        """Sets the is_optimized of this ShiftableMachineCycle.


        :param is_optimized: The is_optimized of this ShiftableMachineCycle.
        :type is_optimized: bool
        """
        if is_optimized is None:
            raise ValueError("Invalid value for `is_optimized`, must not be `None`")  # noqa: E501

        self._is_optimized = is_optimized

    @property
    def power_profile(self):
        """Gets the power_profile of this ShiftableMachineCycle.


        :return: The power_profile of this ShiftableMachineCycle.
        :rtype: List[PowerProfile]
        """
        return self._power_profile

    @power_profile.setter
    def power_profile(self, power_profile):
        """Sets the power_profile of this ShiftableMachineCycle.


        :param power_profile: The power_profile of this ShiftableMachineCycle.
        :type power_profile: List[PowerProfile]
        """
        if power_profile is None:
            raise ValueError("Invalid value for `power_profile`, must not be `None`")  # noqa: E501

        self._power_profile = power_profile
