# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service.models.device import Device
from device_manager_service import util

from device_manager_service.models.device import Device  # noqa: E501

class UserDeviceList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id=None, devices=None):  # noqa: E501
        """UserDeviceList - a model defined in OpenAPI

        :param user_id: The user_id of this UserDeviceList.  # noqa: E501
        :type user_id: str
        :param devices: The devices of this UserDeviceList.  # noqa: E501
        :type devices: List[Device]
        """
        self.openapi_types = {
            'user_id': str,
            'devices': List[Device]
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'devices': 'devices'
        }

        self._user_id = user_id
        self._devices = devices

    @classmethod
    def from_dict(cls, dikt) -> 'UserDeviceList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserDeviceList of this UserDeviceList.  # noqa: E501
        :rtype: UserDeviceList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self):
        """Gets the user_id of this UserDeviceList.


        :return: The user_id of this UserDeviceList.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserDeviceList.


        :param user_id: The user_id of this UserDeviceList.
        :type user_id: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501
        if user_id is not None and len(user_id) > 10:
            raise ValueError("Invalid value for `user_id`, length must be less than or equal to `10`")  # noqa: E501
        if user_id is not None and len(user_id) < 10:
            raise ValueError("Invalid value for `user_id`, length must be greater than or equal to `10`")  # noqa: E501

        self._user_id = user_id

    @property
    def devices(self):
        """Gets the devices of this UserDeviceList.


        :return: The devices of this UserDeviceList.
        :rtype: List[Device]
        """
        return self._devices

    @devices.setter
    def devices(self, devices):
        """Sets the devices of this UserDeviceList.


        :param devices: The devices of this UserDeviceList.
        :type devices: List[Device]
        """
        if devices is None:
            raise ValueError("Invalid value for `devices`, must not be `None`")  # noqa: E501

        self._devices = devices
