# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from device_manager_service.models.base_model_ import Model
from device_manager_service import util


class WashingProgram(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NONE = "none"
    COTTON = "cotton"
    EASY_CARE = "easy_care"
    MIX = "mix"
    DELICATES_SILK = "delicates_silk"
    WOOL = "wool"
    SENSITIVE = "sensitive"
    AUTO30 = "auto30"
    AUTO40 = "auto40"
    AUTO60 = "auto60"
    CHIFFON = "chiffon"
    CURTAINS = "curtains"
    DARK_WASH = "dark_wash"
    DESSOUS = "dessous"
    MONSOON = "monsoon"
    OUTDOOR = "outdoor"
    PLUSH_TOY = "plush_toy"
    SHIRTS_BLOUSES = "shirts_blouses"
    SPORT_FITNESS = "sport_fitness"
    TOWELS = "towels"
    WATER_PROOF = "water_proof"
    def __init__(self):  # noqa: E501
        """WashingProgram - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'WashingProgram':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WashingProgram of this WashingProgram.  # noqa: E501
        :rtype: WashingProgram
        """
        return util.deserialize_model(dikt, cls)
